//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ryoau
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbOkulEntities : DbContext
    {
        public dbOkulEntities()
            : base("name=dbOkulEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAlanlar> tblAlanlar { get; set; }
        public virtual DbSet<tblKulupler> tblKulupler { get; set; }
        public virtual DbSet<tblOgrenciler> tblOgrenciler { get; set; }
        public virtual DbSet<tblSiniflar> tblSiniflar { get; set; }
    }
}
