//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ryoau
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOgrenciler
    {
        public int id { get; set; }
        public string adi { get; set; }
        public string no { get; set; }
        public string sinifi { get; set; }
        public string kulubu { get; set; }
        public string alani { get; set; }
        public Nullable<bool> durumu { get; set; }
    }
}
